name: Go Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vuln-scan:
    name: Run Go Vulnerability Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Go Vulnerability Scanner
        uses: debug-ing/go-vuln-scanner@v1.0.0
